---
exclude_paths:
  - "**/Pods/**/*"
  - "**/Source/**/*View.swift"
  - "**/CutBoxUnitTests/**/*"
  - "**/cutbox_command/**/*"
  - "**/bin/*"
  - "**/docs/*"
  - "./*"
  - "./.*"
  - "**.sh"
  - "**.json"
  - "**.md"
  - "**.yml"
  - "**.png"
  - "**.lock"
  - "**.xml"
  - "**.html"
  - "**.css"
  - "**.js"
  - "**.template"
