disabled_rules: # rule identifiers to exclude from running
  - function_body_length
  - function_parameter_count
  - identifier_name
  - nesting
  - private_over_fileprivate

opt_in_rules: # some rules are only opt-in
  - control_statement
  - empty_count
  - trailing_newline
  - colon
  - comma

included: # paths to include during linting. `--path` is ignored if present.
  - ./**/CutBox/Source
  - ./**/CutBoxUnitTests

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - ./**/Pods/

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly. Give warning only for force casting
force_try: warning # explicitly. Give warning only for force try

type_body_length:
  - 800 # warning
  - 1000 # error

file_length:
  warning: 800
  error: 1000

large_tuple: # warn user when using 5 values in tuple, give error if there are 8
   - 5
   - 8

# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 2 # only warning
  max_length: # warning and error
    warning: 80
    error: 120
  excluded: iPhone # excluded via string
  allowed_symbols: "_"
reporter: "xcode"

empty_count:
  severity: warning
