brew "coreutils"
brew "node" unless system "which node"
brew "go" unless system "which go"
brew "ripgrep" unless system "which rg"
brew "cmark" unless system "which cmark"
brew "cocoapods" unless system "which pod"
brew "carthage" unless system "which carthage"
