#!/bin/sh

# Check script requirements
if [[ "$(which semver)" == "semver not found" ]]; then
  echo "Error: semver required (via Node/npm install -g semver)"
  exit 1
fi

TAG_VERSIONNUM=$(semver $(git tag) | tail -1)
VERSIONNUM=$(/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" "${PROJECT_DIR}/${INFOPLIST_FILE}")

TAG_PATCH=$(echo $TAG_VERSIONNUM | awk -F "." '{print $3}')
PATCH=$(echo $VERSIONNUM | awk -F "." '{print $3}')

NEWPATCH=$(($PATCH + 1))

NEWVERSIONSTRING=$(echo $VERSIONNUM | awk -F "." '{print $1 "." $2 ".'$NEWPATCH'" }')

if [[ $TAG_PATCH == $PATCH ]]; then
  /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $NEWVERSIONSTRING" "${PROJECT_DIR}/${INFOPLIST_FILE}"
else
  echo "warning: Version (${VERSIONNUM}) is already ahead of latest git tag (${TAG_VERSIONNUM})"
fi
