name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - jasonm23
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.5.1
        - 1.5.0
        - Older than 1.5.0? Please update and try to reproduce the bug.
    validations:
      required: true
  - type: dropdown
    id: MacArchitecture
    attributes:
      label: What kind of Mac are you using?
      options:
        - x86 Intel
        - M1 (not currently supported)
        - M2 (not currently supported)
        - M3 (not currently supported)

  - type: dropdown
    id: MacOS
    attributes:
      label: What version of MacOS are you seeing the problem on?
      multiple: true
      options:
        - 10.13 High Sierra
        - 10.14 Mojave
        - 10.15 Catalina
        - 11.x Big Sur
        - 12.x Monterey
