//
//  CutBoxUnitTests-CutBoxMocks.generated.swift
//  CutBox
//
//  Generated by Mockingbird v0.20.0.
//  DO NOT EDIT
//

// swiftlint:disable all

@testable import CutBox
@testable import Mockingbird
import AppKit
import AppKit.NSColor
import Carbon
import Carbon.HIToolbox
import Cocoa
import CoreImage
import Foundation
import JavaScriptCore
import KeyHolder
import Magnet
import RxCocoa
import RxSwift
import ServiceManagement
import Swift
import SwiftyStringScore

// No mocks used in 'CutBoxUnitTests'. Mockingbird is configured to only generate mocks for types
// that are explicitly initialized in your tests with `mock(SomeType.self)`. For more information,
// see 'Thunk Pruning' in the README.
