name: Xcode - Build and Analyze

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_run:

jobs:
  build:
    name: CutBox Build
    runs-on: macos-bigsur

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        run: |
          bin/setup

      - name: Build
        run: |
          bin/build
