name: CutBox Test/Build CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    name: CutBox Build
    runs-on: macos-11
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Brew info
        run: |
          brew info --json --installed

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        run: |
          bin/setup

      - name: Test
        run: |
          bin/test

      - name: Build
        run: |
          bin/build_ci

      - name: Make DMG
        run: |
          bin/cutbox_make_dmg CutBox.dmg

      - name: Get Release Info
        run: |
          echo "RELEASE=$(bin/dev_version)-$(bin/build_number)" >> $GITHUB_ENV

      - name: Release Info
        run: echo ${{ env.RELEASE }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.RELEASE }}
          release_name: ${{ env.RELEASE }}
          draft: true

      - name: Upload CutBox.dmg
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: CutBox.dmg
          asset_name: CutBox-${{env.RELEASE}}.dmg
          asset_content_type: application/octet-stream

      - name: Update Info.plist
        run: |
          git add CutBox/CutBox/Info.plist
          git commit -m "CutBox Release: ${{env.RELEASE}}"
          git push origin master
          git show

#### TODO :
#### Web update
#### Update Homebrew tap
