name: CutBox Test/Build CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    name: CutBox Build
    runs-on: macos-11

    steps:
      - name: Brew info
        run: |
          brew info --json --installed

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        run: |
          bin/setup

      ### - name: Test
      ###   run: |
      ###     bin/test_ci

      - name: Build
        run: |
          bin/build

      - name: Make DMG
        run: |
          bin/cutbox_make_dmg CutBox.dmg

      - name: Get Release Info
        run: |
          echo "RELEASE=$(bin/dev_version)-$(bin/build_number)" >> $GITHUB_ENV

      - name: Test GitHub Environment
        run: echo ${{ env.RELEASE }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          REL:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE }}
          release_name: ${{ env.RELEASE }}
          draft: true

#### TODO :
#### Web update
#### Update Homebrew tap
