name: CutBox Test/Build CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    name: CutBox Build
    runs-on: macos-11

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        run: |
          bin/setup

      - name: Test
        run: |
          bin/test_ci

      - name: Build
        run: |
          bin/build

      - name: Get Release Info
        run: |
          export REL="$(bin/dev_version)-$(bin/build_number)"

      - name: Make DMG
        run: |
          bin/cutbox_make_dmg CutBox.dmg

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.REL }}
          release_name: ${{ env.REL }}
          draft: true

#### TODO :
#### Web update
#### Update Homebrew tap
