target 'CutBox' do
  use_frameworks!
  platform :osx, '10.10'

  pod 'HotKey'
  pod 'RxSwift'
  pod 'RxCocoa'

  abstract_target 'Testing' do
    platform :osx, '10.13'

    pod 'Quick'
    pod 'Nimble'

    target 'CutBoxTests' do
    end

    target 'CutBoxUITests' do
    end
  end
end
