target 'CutBox' do
    use_frameworks!
    platform :osx, '10.13'

    pod 'KeyHolder'
    pod 'Sparkle'
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'SwiftyStringScore',  git: 'git@github.com:8bytes/SwiftyStringScore'

    abstract_target 'Testing' do
        platform :osx, '10.13'

        pod 'RxSwift'
        pod 'Quick'
        pod 'Nimble'

        target 'CutBoxTests' do
        end

    end
end
